import Navbar from '@/Component/Navbar/Navbar'
import './globals.css'
import { BsWhatsapp } from 'react-icons/bs'
import Link from "next/link";

export const metadata = {
  title: 'Nahid Hossain',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body >

        <div> <Navbar></Navbar> </div>


        <div className="  min-h-[calc(100vh-20vh)] ">
          <div className='  mt-20'>
            {children}
          </div>
       </div>
      </body>
    </html>
  )
}
